name: "Generate new release"

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Generate new release
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.8'
          java-package: jdk
          architecture: x64 

      - name: Java Version
        run: java -version

      - name: Set gradlew URL
        run: bash ./LearningMachine/gradlew wrapper --gradle-version 3.4.0 --distribution-type=all
      
      - name: Update gradlew
        run: bash ./LearningMachine/gradlew wrapper
#         run: bash ./LearningMachine/gradlew tasks --all --stacktrace
