name: "Generate new release"

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Generate new release
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build *.apk
        run: bash ./LearningMachine/gradlew wrapper --gradle-version 3.4.0
#         run: bash ./LearningMachine/gradlew tasks --all --stacktrace
